### ISSUE TITLE
Repository restructuring

### ISSUE THREAD

**Issue by ThompsonA93** [ThompsonA93/C-Slurm-Benchmark#1]
Hit approve if you think it'd be a good idea to restructure the project in the following manner:

- A directory for each separate task
- More concise makefiles
- Workflow improvement

Proposed project structure:
```
root
| - *.sh
| - *.md
| - .github/workflows
| - documentation/reports
| - dependence analytics
| - performance analytics
    | - omp
        | - *.c
        | - Makefile
        | - *.md
    | - sorting
        | - *.c
        | - Makefile
        | - *.md
    | - arithmetic 
        | - *.c
        | - Makefile
        | - *.md
```

**Comment by orazefabian** [comment]
looks good to me, but keep in mind this is not software engineering xD

**Comment by chrisswd** [comment]
I think to structure the files relating the topics would be a good idea, but in our case I would prefere a much simpler way without any complex make files. Since this is not SE, the best solution for me is:
* A solution that fits as a whole in one file (containing commands to compile in the comments)
* A solution that A.P. can easily follow.
* A solution that is easy to present in class and instantaneously modifiable.
Cheers
